name: integration

on:
  push:
    branches: [main, test-me-*]
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  dim:
    timeout-minutes: 10

    strategy:
      matrix:
        include:
          - toxenv: py37-dim
          - toxenv: py38-dim
          - toxenv: py39-dim
          - toxenv: py310-dim

    runs-on: ubuntu-latest

    steps:
      - name: Checkout v2
        # Required to mount the Github Workspace to a volume
        uses: actions/checkout@v2

      - name: Pull image and run tests
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image: ghcr.io/proxystore/proxystore-dim:nightly
          options: -v ${{ github.workspace }}:/proxystore --network host --workdir /proxystore
          run: |
            python3.9 -m pip install -r requirements-dev.txt
            python3.9 -m pip install .
            python3.9 -m pip install .[endpoints]
            python3.9 -m pip install git+https://github.com/rapidsai/ucx-py.git
            python3.9 -m pip install pytest
            python3.9 -m pytest -k "[ucx_store]" -s --log-cli-level debug tests/store/store_basics_test.py tests/store/store_proxy_test.py
